version: '3.2'

services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - "3000:3000"
    environment:
    - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
    - /opt/grafana/data:/var/lib/grafana
    depends_on:
    - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - "9090:9090"
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/data
    volumes:
    - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - /opt/prometheus/data:/data
    depends_on:
    - cadvisor
    - node_exporter
    extra_hosts:
      prometheus.inside-cluster.k8s: 10.73.0.66

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - "8080:8080"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
    - "9100:9100"
    volumes:
    - /:/host:ro
    command:
    - --path.rootfs=/host

networks:
  default:
    name: monitor
